
trigger:
- master

pool: 'Azure Pipelines (self-hosted)'

stages:
- stage: Passo1
  displayName: 'Instalações Necessárias'
  
  jobs:
  - job: Execution_Pipeline
    displayName: 'Validação do Pipeline de Testes'

    steps:
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '16'
      displayName: 'Instalar o Node.js'

    - script: npm install -g yarn
      displayName: 'instalação do Yarn'

    - script: yarn
      displayName: 'Instalando dependências'

    - script: yarn playwright install
      displayName: 'Instalando o playwright'
      
    - script: yarn run e2e
      displayName: 'Executando testes e2e'
   

    - task: PublishAllureReport@2
      inputs:
        allureVersion: '2.27.0'
        testResultsDir: 'allure-results'
        reportName: 'Report'