
trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: AutomatedTesting
  displayName: 'Testes Automatizados'
  
  jobs:
  - job: Execution_Pipeline
    displayName: 'Validação do Pipeline de Testes'

    steps:
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '16'
      displayName: 'Instalar o Node.js'

    - script: npm install -g yarn
      displayName: 'instalação do Yarn'

    - script: yarn
      displayName: 'Instalando dependências'

    - script: yarn playwright install
      displayName: 'Instalando o playwright'

    - script: yarn run e2e
      displayName: 'Executando testes e2e'
